# -*- coding: utf-8 -*-
"""open_npz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uhILCwzeIChs5qyX1a9VR0nUd-NP-khi
"""

import os
import sys

import numpy as np
from numpy import asarray
from PIL import Image


def count_occurences(matrix):
    occurences = {}
    for row in matrix:
        for num in row:
            if num in occurences:
                occurences[num] += 1
            else:
                occurences[num] = 1
    return occurences


def main():
    filename = input("Enter the path to the .npz file: ")
    # Load the .npz file
    data = np.load(filename)

    # Access the arrays saved in the .npz file
    for key in data.keys():
        print(f"Array name: {key}")
        print(data[key])

        # Get the dimensions of the array
        dimensions = data[key].shape
        print("Dimensions of the 2D array:", dimensions)

        result = count_occurences(data[key])
        sorted_keys = sorted(result.keys())

        print("Occurrences:")
        for key in sorted_keys:
            print(f"{key}: {result[key]}")

    file_size = os.path.getsize(filename)
    print("File size:", file_size, "bytes")


if __name__ == "__main__":
    main()
